CREATE TABLE IF NOT EXISTS Voter (
    PersonID VARCHAR(50) NOT NULL,
    lastVotedRound TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (PersonID),
    FOREIGN KEY (PersonID) REFERENCES Person(ID) ON DELETE CASCADE ON UPDATE CASCADE
);